import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

// const inter = Inter({ subsets: ["latin"] });
import dynamic from "next/dynamic";
import { lazy } from "react";

// const Product = lazy(() => import("remote_component/Product"));
// const Product = dynamic(() => import("remote_component/Product"));

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>all Products</h1>
      </main>
    </>
  );
}
