import Head from "next/head";
import Image from "next/image";

// const inter = Inter({ subsets: ["latin"] });
import dynamic from "next/dynamic";
import { lazy } from "react";
import ProductItem from "@/components/ProductItem";

// const Product = lazy(() => import("remote_component/Product"));
// const Product = dynamic(() => import("remote_component/Product"));
export async function getStaticProps() {
  try {
    const res = await fetch("https://fakestoreapi.com/products");
    const products = await res.json();
    return {
      props: {
        products,
      },
    };
  } catch (error) {
    console.log(error);
    return {
      props: {
        products: [],
      },
    };
  }
}

export default function Home({ products }) {
  console.log(products);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ul>
          {products.map((product, index) => (
            <ProductItem key={index} product={product}></ProductItem>
          ))}
        </ul>
      </main>
    </>
  );
}
